name: Release Draft

on:
  workflow_call:
    inputs: 
      username:
        description: 'Name of user to run workflow'
        type: string
        required: true
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Use Node.js latest
         uses: actions/setup-node@v3
         with:
           node-version: latest
       - name: Install dependencies
         run: npm install
       - name: Build
         run: npm run build
       - name: Create a release draft for a version tag
         id: create-release-draft
         uses: release-drafter/release-drafter@v5
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
